<a href="https://colab.research.google.com/github/ris2002/AI_python/blob/main/Neural_Network_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Modelling a single neuron with 4 inputs and 1 bias**

In [ ]:
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

In [ ]:
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
output

4.8

**Modelling a neuron layer with 4 input neurons and 1 hidden layer with 3 neurons in it**

In [ ]:
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1.0]
bias1=2
weights2=[0.5,-0.91,0.26,-0.5]
bias2=3
weights3=[-0.26,-0.27,0.17,0.87]
bias3=0.5
output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
output

[4.8, 1.21, 2.385]

Coding the above in more dynamic way

In [ ]:

weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
inputs=[1,2,3,2.5]
def dynamic_outputs(weights,biases,inputs):
  layer_outputs=[]

  for i_weight,bias in zip(weights,biases):
    n_output=0

    for w,input in zip(i_weight,inputs):
      n_output+=w*input
    output=n_output+bias
    layer_outputs.append(output)
  return layer_outputs








In [ ]:
dynamic_outputs(weights,biases,inputs)

[4.8, 1.21, 2.385]

Using Numpy

In [ ]:
import numpy as np
weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
inputs=[1,2,3,2.5]
arr_weights=np.array(weights)
arr_inputs=np.array(inputs)
arr_biases=np.array(biases)

In [ ]:
result=np.dot(arr_weights,arr_inputs)+arr_biases
result

array([4.8  , 1.21 , 2.385])

Batches

In [ ]:
import numpy as np
weights=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
inputs=[[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]
arr_weights=np.array(weights)
arr_inputs=np.array(inputs)
arr_biases=np.array(biases)

In [ ]:
print('weights_shape',np.shape(arr_weights))
print('ip_shape',np.shape(arr_inputs))
x=arr_weights.T

print('transspose_sshape',np.shape(x))


weights_shape (3, 4)
ip_shape (3, 4)
transspose_sshape (4, 3)


In [ ]:
result=np.dot(arr_inputs,x)+arr_biases
result

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

Layering Example

```
# This is formatted as code
```



In [ ]:
import numpy as np
weights=np.array([[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]])
biases=np.array([2,3,0.5])
inputs=np.array([[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]])

weights2=np.array([[0.1,-0.14,0.5],[-0.5,0.12,-0.33],[-0.44,0.73,-0.13]])
biases2=np.array([-1,2,-0.5])
layer_1=np.dot(inputs,weights.T)+biases
layer_2=np.dot(layer_1,weights2.T)+biases2
layer_2


array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

Layering Implementation


In [ ]:
import numpy as np
np.random.seed(0)
X= inputs=np.array([[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]])
class Layer_Dense:
  def __init__(self,n_features,n_neurons):
    self.weights=np.random.rand(n_features,n_neurons)*0.1 # Shape is given like (n_inputs,n_neurons) to prevent transpose in every step
    self.biases=np.zeros((1, n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases


In [ ]:
layer_1=Layer_Dense(4,5)
layer_2=Layer_Dense(5,2)

In [ ]:
layer_1.forward(X)

In [ ]:
print(layer_1.output)

[[0.4254945  0.38354774 0.41052277 0.34251774 0.42920075]
 [0.45990565 0.45926792 0.3557192  0.64262395 0.35073359]
 [0.19206482 0.17652073 0.31805382 0.16418703 0.37220917]]


In [ ]:
layer_2.forward(layer_1.output)
print(layer_2.output)

[[0.11312949 0.04836473]
 [0.13737205 0.05544616]
 [0.06312143 0.02861227]]


Actvation Function RELU CLass

In [ ]:
pip install nnfs

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()


X,y=spiral_data(100,3)
class Layer_Dense:
  def __init__(self,n_features,n_neurons):
    self.weights=np.random.randn(n_features,n_neurons)*0.1 # Shape is given like (n_inputs,n_neurons) to prevent transpose in every step
    self.biases=np.zeros((1, n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases

class Activation_Relu:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        return self.output

In [ ]:
layer_1=Layer_Dense(2,5)
activation_1=Activation_Relu()
layer_1.forward(X)
print('layer_1:',layer_1.output)
activation_1.forward(layer_1.output)


print('Activation_function:',activation_1.forward(layer_1.output))


layer_1: [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 5.09662132e-05  2.82163121e-04 -6.14295888e-04 -2.78327265e-04
  -2.18806133e-04]
 [-2.53826292e-05  1.32260774e-03 -1.89793913e-03 -1.03709206e-03
  -6.62760111e-04]
 ...
 [ 1.49472691e-02 -1.03460461e-01  1.00327469e-01  6.80047795e-02
   3.40471603e-02]
 [ 1.17370244e-02 -1.04946040e-01  1.14487566e-01  7.24482983e-02
   3.92385311e-02]
 [ 1.57508273e-02 -1.03014432e-01  9.66713205e-02  6.68329149e-02
   3.27085815e-02]]
Activation_function: [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [5.09662132e-05 2.82163121e-04 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 1.32260774e-03 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 ...
 [1.49472691e-02 0.00000000e+00 1.00327469e-01 6.80047795e-02
  3.40471603e-02]
 [1.17370244e-02 0.00000000e+00 1.14487566e-01 7.24482983e-02
  3.92385311e-02]
 [1.57508273e-02 0.00000000e+00 9.66713205e-02 6.

Adding softmax activation

In [ ]:
import math
E=math.e
layer_outputs=[4.8,1.21,2.385]
exp_vals=[]
op=[]
for output in layer_outputs:
  exp_vals.append(E**output)
total=sum(exp_vals)
for x in exp_vals:
  y=x/total
  op.append(y)
op



0.9999999999999999

In [ ]:
import numpy as np
import math
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
class Hidden_Layers:
  def __init__(self,n_features,n_neurons):
    self.weights=np.random.randn(n_features,n_neurons)*0.1
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
    return self.output
  def activation_relu(self,input):
    self.output=np.maximum(0, input)
    return self.output
  def activation_softmax(self,input):
    exp_vals=np.exp(input-np.max(input,axis=1,keepdims=True))
    self.output=exp_vals/np.sum(exp_vals,axis=1,keepdims=True)
    return self.output




ModuleNotFoundError: No module named 'nnfs'

In [ ]:
X,y=spiral_data(100,3)

In [ ]:
dense=Hidden_Layers(2,3)
x=dense.forward(X)
relu=dense.activation_relu(x)
softmax=dense.activation_softmax(relu)
print(softmax)

[[0.33333334 0.33333334 0.33333334]
 [0.33320668 0.33358663 0.33320668]
 [0.33298057 0.3340388  0.33298057]
 [0.33274764 0.33450472 0.33274764]
 [0.33253902 0.33492193 0.33253902]
 [0.33294392 0.33411214 0.33294392]
 [0.33213475 0.33573046 0.33213475]
 [0.33213967 0.33572063 0.33213967]
 [0.3318732  0.3362536  0.3318732 ]
 [0.33152837 0.3369432  0.33152837]
 [0.33133313 0.33733377 0.33133313]
 [0.33156234 0.33684665 0.33159104]
 [0.331113   0.337774   0.331113  ]
 [0.33076087 0.33847824 0.33076087]
 [0.33079228 0.33841544 0.33079228]
 [0.33067313 0.3386537  0.33067313]
 [0.33165532 0.33537307 0.3329716 ]
 [0.33021405 0.3395719  0.33021405]
 [0.33062845 0.33830744 0.33106408]
 [0.3296771  0.34064573 0.3296771 ]
 [0.3296932  0.34061363 0.3296932 ]
 [0.33138767 0.33525944 0.3333529 ]
 [0.3320031  0.33338803 0.33460885]
 [0.32982793 0.3398703  0.3303018 ]
 [0.33828804 0.3289749  0.33273706]
 [0.32919678 0.3416064  0.32919678]
 [0.33173904 0.33345756 0.33480337]
 [0.3316102  0.33364385 0.33


```

Implementing Categorical Cross Entropy




```



In [ ]:
pip install nnfs

In [ ]:
import numpy as np
np.random.seed(0)
import math
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
class Hidden_Layers:
  def __init__(self,n_features,n_neurons):
    self.weights=np.random.randn(n_features,n_neurons)*0.01
    self.biases=np.zeros(n_neurons)
  def forward(self,inputs):
    self.outputs=np.dot(inputs,self.weights)+self.biases
class Activation_Function():
  def relu_activation(self,input):
    self.relu_output=np.maximum(0,input)
  def activation_softmax(self,input):
    exp_vals=np.exp(input-np.max(input,axis=1,keepdims=True))
    self.softmax_output=exp_vals/np.sum(exp_vals,axis=1,keepdims=True)
class Loss:
  def calculate(self,output,y):
    sample_losses=self.forward(output,y)
    data_loss=np.mean(sample_losses)
    return data_loss
class Cross_Entropy(Loss):
  def forward(self,y_pred,y_true):
    clipped_output=np.clip(y_pred,1e-7,1-1e-7)# to make 0s to 0.000001 or nearnest no. cos log(0) gives error
    samples=len(y_pred)
    if len(y_true.shape)==1:
      correct_confidences=clipped_output[range(samples),y_true] # to handle data if thethe true values are in scalar form

    elif len(y_true.shape)==2:
      correct_confidences=np.sum(clipped_output*y_true,axis=1) # to handle daata if the y true values are in OHE form
    output=-np.log(correct_confidences)
    return output



In [ ]:
X,y=spiral_data(100,3)

In [ ]:
layer_1=Hidden_Layers(2,3)
layer_1.forward(X)
print(layer_1.outputs)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.04751882e-04  1.13953611e-04 -4.79834998e-05]
 [-2.74148420e-04  3.17291502e-04 -8.69217984e-05]
 [-4.21883655e-04  5.26662567e-04 -5.59126820e-05]
 [-5.77076804e-04  7.14014051e-04 -8.94304394e-05]
 [-3.54306976e-04  3.50254879e-04 -2.33634812e-04]
 [-8.92670010e-04  1.07678759e-03 -1.94532375e-04]
 [-9.33507807e-04  1.07238023e-03 -3.12273973e-04]
 [-1.12437585e-03  1.31128007e-03 -3.36296740e-04]
 [-1.33869553e-03  1.62009057e-03 -2.81017943e-04]
 [-1.48779724e-03  1.79484230e-03 -3.23859538e-04]
 [-1.20035873e-03  1.58119109e-03  8.65937000e-06]
 [-1.56528328e-03  1.99173321e-03 -1.30997345e-04]
 [-1.85718178e-03  2.30642664e-03 -2.70479388e-04]
 [-1.78093580e-03  2.27836682e-03 -1.24245722e-04]
 [-1.85300526e-03  2.38476763e-03 -1.00471654e-04]
 [-6.99865050e-04  1.11472746e-03  3.96097894e-04]
 [-2.19024252e-03  2.79446482e-03 -1.68075712e-04]
 [-1.69829139e-03  2.29598465e-03  1.31671681e-04]
 [-2.60229013e-03  3.27291898e-

In [ ]:
act=Activation_Function()
act.relu_activation(layer_1.outputs)
print(act.relu_output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.13953611e-04 0.00000000e+00]
 [0.00000000e+00 3.17291502e-04 0.00000000e+00]
 [0.00000000e+00 5.26662567e-04 0.00000000e+00]
 [0.00000000e+00 7.14014051e-04 0.00000000e+00]
 [0.00000000e+00 3.50254879e-04 0.00000000e+00]
 [0.00000000e+00 1.07678759e-03 0.00000000e+00]
 [0.00000000e+00 1.07238023e-03 0.00000000e+00]
 [0.00000000e+00 1.31128007e-03 0.00000000e+00]
 [0.00000000e+00 1.62009057e-03 0.00000000e+00]
 [0.00000000e+00 1.79484230e-03 0.00000000e+00]
 [0.00000000e+00 1.58119109e-03 8.65937000e-06]
 [0.00000000e+00 1.99173321e-03 0.00000000e+00]
 [0.00000000e+00 2.30642664e-03 0.00000000e+00]
 [0.00000000e+00 2.27836682e-03 0.00000000e+00]
 [0.00000000e+00 2.38476763e-03 0.00000000e+00]
 [0.00000000e+00 1.11472746e-03 3.96097894e-04]
 [0.00000000e+00 2.79446482e-03 0.00000000e+00]
 [0.00000000e+00 2.29598465e-03 1.31671681e-04]
 [0.00000000e+00 3.27291898e-03 0.00000000e+00]
 [0.00000000e+00 3.25863226e-03 0.000000

In [ ]:
act.activation_softmax(act.relu_output)
print(act.softmax_output)

[[0.33333334 0.33333334 0.33333334]
 [0.33332068 0.33335868 0.33332068]
 [0.3332981  0.33340386 0.3332981 ]
 [0.3332748  0.3334504  0.3332748 ]
 [0.33325398 0.33349204 0.33325398]
 [0.33329442 0.3334112  0.33329442]
 [0.33321366 0.33357266 0.33321366]
 [0.33321416 0.33357167 0.33321416]
 [0.33318758 0.33362478 0.33318758]
 [0.33315328 0.33369344 0.33315328]
 [0.33313385 0.3337323  0.33313385]
 [0.33315665 0.33368385 0.33315954]
 [0.33311194 0.33377612 0.33311194]
 [0.33307695 0.3338461  0.33307695]
 [0.33308008 0.3338398  0.33308008]
 [0.33306825 0.3338635  0.33306825]
 [0.33316547 0.33353707 0.33329746]
 [0.33302268 0.3339546  0.33302268]
 [0.3330635  0.3338291  0.33310738]
 [0.33296946 0.33406103 0.33296946]
 [0.33297107 0.33405784 0.33297107]
 [0.33313859 0.33352578 0.3333356 ]
 [0.33320022 0.33333898 0.33346084]
 [0.332984   0.33398423 0.33303177]
 [0.3338275  0.3328969  0.33327562]
 [0.33292195 0.33415616 0.33292195]
 [0.3331738  0.33334595 0.33348027]
 [0.33316085 0.33336458 0.33

In [ ]:
loss=Cross_Entropy()

y_pred = act.softmax_output
y_true = y
print(loss.calculate(y_pred, y_true))


1.0985671
